### ISSUE TITLE
Suggestion: use a config file for API tokens

### ISSUE THREAD

**Issue by liamphmurphy** [torlenor/abylebotter#9]
This is just a suggestion. If you like it I'd be happy to work on it.

Instead of using env variables, I suggest creating a config that can store the API keys that the bot requires. Probably a config file for each service separately (discord, matrix etc). I recommend TOML, but this would require getting a third-party driver.

I've done this for my own Twitch bot and is pretty straightforward.

**Comment by torlenor** [comment]
I do like the idea in general, but I don't want to lose the flexibility of using environment variables, especially regarding deployment in Docker. A mixed approach like Gitlab does it with its containers would be my preferred way to go. They are using a config file which you could edit, but also make it possible to override nearly everything with environment variables, but I haven't looked into that, yet.

**Comment by torlenor** [comment]
I decided I will use a config file after all and for now implement some overwrites via env variables by hand.
Planed config file structure (at least for now):

```
[bots]

  [bots.discord]
  enabled = true
  token = "INSERT_DISCORD_TOKEN_HERE" # can be overwritten via env variable DISCORD_TOKEN

    [bots.discord.plugins.echo]
    enabled = true

    [bots.discord.plugins.giveaway]
    enabled = true

  [bots.matrix]
  enabled = false
  server = "INSERT_MATRIX_SERVER_HERE" # can be overwritten via env variable MATRIX_SERVER
  username = "INSERT_MATRIX_USER_HERE" # can be overwritten via env variable MATRIX_USERNAME
  password = "INSERT_MATRIX_PASSWORD_HERE" # can be overwritten via env variable MATRIX_PASSWORD

    [bots.matrix.plugins.echo]
    enabled = false

    [bots.matrix.plugins.giveaway]
    enabled = false
```
Not sure what parser. Maybe I will go with [https://github.com/BurntSushi/toml](url).

**Comment by liamphmurphy** [comment]
I highly recommend the parse you linked. I use it to read the config file I have for my Twitch bot and is very easy to use once you get any necessary structs put together.

**Comment by torlenor** [comment]
Implemented parsing of the config file structure from above. Is a bit manual work to extend it to different bots and plugins, but can be refactored when needed.
